steps:
  build:
    image: danog/gojekyll
    when:
      branch: master
      event: push
    environment:
      DEPLOY_KEY:
        from_secret: DEPLOY_KEY
    commands:
      - apt-get update && apt-get -y install openssh-client git
      - mkdir -p $HOME/.ssh
      - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
      - echo "$DEPLOY_KEY" > $HOME/.ssh/id_rsa
      - chmod 0600 $HOME/.ssh/id_rsa
      - git config --global user.email "daniil@daniil.it"
      - git config --global user.name "Daniil Gentili"
      - git remote add o git@github.com:danog/MadelineProtoDocs.git 
      - cd docs
      - gojekyll build
      - rm -rf /tmp/_site
      - cp -a _site /tmp/
      - cd ..
      - git branch -D gh-pages || true
      - git switch --orphan gh-pages
      - cp -a /tmp/_site/* .
      - git add -A
      - git commit -am 'Update'
      - git push -f o gh-pages
